server:
  port: 8083

spring:
  application:
    name: Rating-Service

  datasource:
    url: jdbc:mysql://localhost:3306/rating_service
    username: root
    password: Ashu@123

  jpa:
    hibernate:
      ddl-auto: update